### ISSUE TITLE
RFC subseries `<referencegroup target="...">` and `<reference target="...">` values not reflecting correct `target`

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#140]
This is the original BibXML from the legacy dataset:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0048.xml
```xml
<referencegroup anchor="BCP48" target="https://www.rfc-editor.org/info/bcp48">
<!--  reference.RFC.3150.xml  -->
<reference anchor="RFC3150" target="https://www.rfc-editor.org/info/rfc3150">
<front>
<title>End-to-end Performance Implications of Slow Links</title>
<author initials="S." surname="Dawkins" fullname="S. Dawkins">
<organization/>
</author>
<author initials="G." surname="Montenegro" fullname="G. Montenegro">
<organization/>
</author>
<author initials="M." surname="Kojo" fullname="M. Kojo">
<organization/>
</author>
<author initials="V." surname="Magret" fullname="V. Magret">
<organization/>
</author>
<date year="2001" month="July"/>
<abstract>
<t>
This document makes performance-related recommendations for users of network paths that traverse "very low bit-rate" links. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="BCP" value="48"/>
<seriesInfo name="RFC" value="3150"/>
<seriesInfo name="DOI" value="10.17487/RFC3150"/>
</reference>
</referencegroup>
```

Notice that the source data provides the proper links:

https://github.com/ietf-ribose/relaton-data-rfcsubseries/blob/d3fe30d9e5860f9e4c6fef815fda5fd9ec52c3b9/data/BCP0048.yaml#L3-L5
```yaml
link:
- content: https://www.rfc-editor.org/info/bcp48
  type: src
```

and

https://github.com/ietf-ribose/relaton-data-rfcsubseries/blob/d3fe30d9e5860f9e4c6fef815fda5fd9ec52c3b9/data/BCP0048.yaml#L37-L41
```yaml
    link:
    - content: https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml
      type: xml
    - content: https://www.rfc-editor.org/info/rfc3150
      type: src
```

However, the BibXML service BibXML has two problems:
1. Does not contain the target for `referencegroup` `target`;
2. Does not have the correct target for `reference` target`
https://dev.bibxml.org/api/v1/by-docid/?doctype=IETF&docid=BCP%2048&format=bibxml

```xml
<?xml version="1.0"?>
<referencegroup>
  <reference target="https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml">
    <front>
      <title>End-to-end Performance Implications of Slow Links</title>
      <author fullname="S. Dawkins" surname="Dawkins" initials="S"/>
      <author fullname="G. Montenegro" surname="Montenegro" initials="G"/>
      <author fullname="M. Kojo" surname="Kojo" initials="M"/>
      <author fullname="V. Magret" surname="Magret" initials="V"/>
      <date year="2001" month="July"/>
      <abstract>
        <t>
This document makes performance-related recommendations for users of network paths that traverse "very low bit-rate" links. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
      </abstract>
    </front>
    <seriesInfo name="DOI" value="10.17487/RFC3150"/>
    <seriesInfo name="RFC" value="3150"/>
    <seriesInfo name="BCP" value="48"/>
  </reference>
</referencegroup>
```

<details>
  <summary>Relaton JSON</summary>

  ```json
  {
    "data": {
      "formattedref": {
        "content": "BCP48",
        "format": "text/plain",
        "script": [
          "Latn"
        ],
        "language": [
          "en"
        ]
      },
      "docid": [
        {
          "id": "BCP 48",
          "type": "IETF",
          "primary": true,
          "scope": null
        },
        {
          "id": "BCP0048",
          "type": "IETF",
          "primary": null,
          "scope": "anchor"
        }
      ],
      "docnumber": "BCP0048",
      "language": [
        "en"
      ],
      "type": "standard",
      "doctype": null,
      "script": [
        "Latn"
      ],
      "date": null,
      "link": [
        {
          "content": "https://www.rfc-editor.org/info/bcp48",
          "type": "src"
        }
      ],
      "relation": [
        {
          "type": "includes",
          "bibitem": {
            "formattedref": null,
            "docid": [
              {
                "id": "RFC 3150",
                "type": "RFC",
                "primary": true,
                "scope": null
              },
              {
                "id": "RFC3150",
                "type": "RFC",
                "primary": null,
                "scope": "anchor"
              },
              {
                "id": "10.17487/RFC3150",
                "type": "DOI",
                "primary": null,
                "scope": null
              }
            ],
            "docnumber": "RFC3150",
            "language": [
              "en"
            ],
            "type": "standard",
            "doctype": "rfc",
            "script": [
              "Latn"
            ],
            "date": [
              {
                "value": "July 2001",
                "type": "published"
              }
            ],
            "link": [
              {
                "content": "https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml",
                "type": "xml"
              },
              {
                "content": "https://www.rfc-editor.org/info/rfc3150",
                "type": "src"
              }
            ],
            "relation": null,
            "title": [
              {
                "content": "End-to-end Performance Implications of Slow Links",
                "format": "text/plain",
                "script": [
                  "Latn"
                ],
                "language": [
                  "en"
                ],
                "type": null
              }
            ],
            "edition": null,
            "abstract": [
              {
                "content": "<p>This document makes performance-related recommendations for users of network paths that traverse \"very low bit-rate\" links. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.</p>",
                "format": "text/html",
                "script": [
                  "Latn"
                ],
                "language": [
                  "en"
                ]
              }
            ],
            "fetched": "2022-02-14",
            "revdate": "July 2001",
            "biblionote": null,
            "contributor": [
              {
                "role": [
                  "publisher"
                ],
                "person": null,
                "organization": {
                  "name": [
                    "Internet Engineering Task Force"
                  ],
                  "contact": null,
                  "url": null,
                  "abbreviation": "IETF"
                }
              },
              {
                "role": [
                  "author"
                ],
                "person": {
                  "name": {
                    "completename": {
                      "content": "S. Dawkins",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "surname": {
                      "content": "Dawkins",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "initial": [
                      {
                        "content": "S.",
                        "format": null,
                        "script": null,
                        "language": [
                          "en"
                        ]
                      }
                    ],
                    "forename": null
                  },
                  "affiliation": null
                },
                "organization": null
              },
              {
                "role": [
                  "author"
                ],
                "person": {
                  "name": {
                    "completename": {
                      "content": "G. Montenegro",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "surname": {
                      "content": "Montenegro",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "initial": [
                      {
                        "content": "G.",
                        "format": null,
                        "script": null,
                        "language": [
                          "en"
                        ]
                      }
                    ],
                    "forename": null
                  },
                  "affiliation": null
                },
                "organization": null
              },
              {
                "role": [
                  "author"
                ],
                "person": {
                  "name": {
                    "completename": {
                      "content": "M. Kojo",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "surname": {
                      "content": "Kojo",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "initial": [
                      {
                        "content": "M.",
                        "format": null,
                        "script": null,
                        "language": [
                          "en"
                        ]
                      }
                    ],
                    "forename": null
                  },
                  "affiliation": null
                },
                "organization": null
              },
              {
                "role": [
                  "author"
                ],
                "person": {
                  "name": {
                    "completename": {
                      "content": "V. Magret",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "surname": {
                      "content": "Magret",
                      "format": null,
                      "script": null,
                      "language": [
                        "en"
                      ]
                    },
                    "initial": [
                      {
                        "content": "V.",
                        "format": null,
                        "script": null,
                        "language": [
                          "en"
                        ]
                      }
                    ],
                    "forename": null
                  },
                  "affiliation": null
                },
                "organization": null
              }
            ],
            "place": null,
            "series": [
              {
                "formattedref": null,
                "title": {
                  "content": "BCP",
                  "format": "text/plain",
                  "script": [
                    "Latn"
                  ],
                  "language": [
                    "en"
                  ]
                },
                "abbrev": null,
                "place": null,
                "number": "48",
                "organization": null,
                "run": null,
                "partnumber": null,
                "type": "main"
              },
              {
                "formattedref": null,
                "title": {
                  "content": "RFC",
                  "format": "text/plain",
                  "script": [
                    "Latn"
                  ],
                  "language": [
                    "en"
                  ]
                },
                "abbrev": null,
                "place": null,
                "number": "3150",
                "organization": null,
                "run": null,
                "partnumber": null,
                "type": "main"
              }
            ],
            "keyword": null,
            "copyright": null,
            "id": "RFC3150"
          },
          "description": null
        }
      ],
      "title": null,
      "edition": null,
      "abstract": null,
      "fetched": null,
      "revdate": null,
      "biblionote": null,
      "contributor": null,
      "place": null,
      "series": null,
      "keyword": null,
      "copyright": null,
      "id": "BCP48"
    }
  }
  ```
</details>

**Comment by ronaldtse** [comment]
(Update: Moved `anchor` issue to new issue)

**Comment by strogonoff** [comment]
Regarding the anchor, replied in https://github.com/ietf-ribose/bibxml-service/issues/141#issuecomment-1056954591.

**Comment by strogonoff** [comment]
Fixed in https://github.com/ietf-ribose/bibxml-service/commit/183cd358e6d6a0e00780be27a16f9af9a449fcaa.

**Comment by strogonoff** [comment]
Erroneously closed.

**Comment by ronaldtse** [comment]
@strogonoff this issue is still present:
1. The `target` attribute of `<referencegroup>` is missing:
  * now: `<referencegroup anchor="BCP48">`
  * correct: `<referencegroup anchor="BCP48" target="https://www.rfc-editor.org/info/bcp48">`
2. The `target` attribute of `<reference>` is not reflecting the correct URL:
  * now: `<reference target="https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml" anchor="RFC3150">`
  * correct: `<reference anchor="RFC3150" target="https://www.rfc-editor.org/info/rfc3150">`

**Comment by strogonoff** [comment]
@ronaldtse Ah, I think I misunderstood the original description, thinking you wanted `target` to point to BibXML service’s own URLs. I filed #168 and #169, should be done shortly.

**Comment by strogonoff** [comment]
Should be fixed after testing and release

**Comment by strogonoff** [comment]
I believe the targets should be correct now: https://dev.bibxml.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0048.xml

**Comment by ronaldtse** [comment]
@strogonoff thanks! They are indeed correct now.

```xml
<referencegroup anchor="BCP48" target="https://www.rfc-editor.org/info/bcp48">
```

```xml
<reference target="https://www.rfc-editor.org/info/rfc3150" anchor="RFC3150">
```

**Comment by strogonoff** [comment]
@ronaldtse  reopened by mistake? Or is there a problem to fix?

**Comment by strogonoff** [comment]
target more prefers a link with type=src, and is set for both referencegroup and reference elements.

**Comment by ronaldtse** [comment]
Oh sorry, must have pressed command-enter and it reopened...

**Comment by strogonoff** [comment]
Okay, no problem…
